#include "app_adc.h"

// Bring in the ADC handle generated by CubeMX
extern ADC_HandleTypeDef hadc;

void App_ADC_Read_All(uint32_t* ch1_val, uint32_t* ch2_val)
{
    // 1. Arm the ADC (It will wait for the TIM1 pulse to actually sample)
    HAL_ADC_Start(&hadc);

    // 2. Wait for the TIM1 pulse and read PA1 (Positive Peak Voltage)
    if (HAL_ADC_PollForConversion(&hadc, 10) == HAL_OK)
    {
      *ch1_val = HAL_ADC_GetValue(&hadc);
    }

    // 3. Immediately read PA2
    if (HAL_ADC_PollForConversion(&hadc, 10) == HAL_OK)
    {
      *ch2_val = HAL_ADC_GetValue(&hadc);
    }

    // 4. Stop the ADC
    HAL_ADC_Stop(&hadc);
}
