#include "app_adc.h"

// Bring in the ADC handle generated by CubeMX
extern ADC_HandleTypeDef hadc;

void App_ADC_Read_All(uint32_t* ch1_val, uint32_t* ch2_val, uint32_t* ch3_val, uint32_t* ch4_val)
{
    // 1. Arm the ADC
    HAL_ADC_Start(&hadc);

    // 2. Wait for the TIM1 pulse and read PA1
    if (HAL_ADC_PollForConversion(&hadc, 10) == HAL_OK) {
        *ch1_val = HAL_ADC_GetValue(&hadc);
    } else {
        HAL_ADC_Stop(&hadc); return; // ABORT on failure
    }

    // 3. Immediately read PA2
    if (HAL_ADC_PollForConversion(&hadc, 10) == HAL_OK) {
        *ch2_val = HAL_ADC_GetValue(&hadc);
    } else {
        HAL_ADC_Stop(&hadc); return;
    }

    // 4. Wait for TIM1 pulse 3 -> Read PA3
    if (HAL_ADC_PollForConversion(&hadc, 10) == HAL_OK) {
        *ch3_val = HAL_ADC_GetValue(&hadc);
    } else {
        HAL_ADC_Stop(&hadc); return;
    }

    // 5. Read PA4
    if (HAL_ADC_PollForConversion(&hadc, 10) == HAL_OK) {
        *ch4_val = HAL_ADC_GetValue(&hadc);
    } else {
        HAL_ADC_Stop(&hadc); return;
    }

    // 6. Stop the ADC
    HAL_ADC_Stop(&hadc);
}
